### ISSUE TITLE
discrete independent variables crash the analysis

### ISSUE THREAD

**Issue by wkthompson123** [ABCD-STUDY/DEAP#15]
I ran DEAP on internal system (abcd-deap.ucsd.edu) using Chrome on a MacBook Pro. 

When I put in a discrete independent variable for plotting (e.g., race.eth), the analysis does not run.
<img width="1451" alt="screen shot 2018-10-12 at 12 29 32 pm" src="https://user-images.githubusercontent.com/44100683/46890920-1f577980-ce1d-11e8-926a-c47bbf852a1d.png">

**Comment by HaukeBartsch** [comment]
It looks as if the histogram is also broken in this case. Female is created on analysis-nda17 instead of coming from NDA. We need to test if this issue is related. Female is listed as:

{"summary":[{"transform":[],"summary":{"no":2375,"yes":2146}}],"factors":{"Length":"2","Class":"character","Mode":"character"},"histograms":null}

so the histogram should not be there (check for null object in histograms).

**Comment by HaukeBartsch** [comment]
On our abcd-deap.ucsd.edu version I see the following:

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/603956/46895443-3d2cda80-ce2d-11e8-9495-e3c6df29791b.png">

**Comment by Mosqidiot** [comment]
Keeping female and sex together still doesn't compile. Looks like the model has been successfully  generated but failed at qq plot.

**Comment by Mosqidiot** [comment]
Categorical data histogram has been fixed.

**Comment by wkthompson123** [comment]
Can Chase fix this one?

**Comment by HaukeBartsch** [comment]
works now
<img width="844" alt="image" src="https://user-images.githubusercontent.com/603956/47510515-245cf580-d82d-11e8-8300-478bdeaa8a56.png">
