### ISSUE TITLE
sleep_1_p

### ISSUE THREAD

**Issue by lkmcevoy** [ABCD-STUDY/DEAP#28]
tried to include as a dependent measure, get this error
Error: 'sleep_1_p' variable has <2 unique values
but histogram shows values in all 5 categories.

**Comment by HaukeBartsch** [comment]
This seems to be working for me. Maybe you have some other missing variable in the model that is removing all data? Or, you have tried to run the model during an update.

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/603956/47189720-cf802300-d2f2-11e8-98ae-b32be12c065a.png">

**Comment by HaukeBartsch** [comment]
This seems to be caused by sleep_1_p being a categorical variable. If you create a continuous version of this variable. For example in Extend you will see that the analysis runs.

### A numeric version of a categorical variable

```
var promises = use(["sleep_1_p"]);
```
In this case we have to list all levels and map them to a number. Here we are using the mean of the range.
```
function mapNumeric(v) {
    if (v == "9-11 hours")
        return 10;
     if (v == "8-9 hours")
        return 8.5;
     if (v == "7-8 hours")
        return 7.5;
     if (v == "5-7 hours")
        return 6;
     if (v == "Less than 5 hours")
        return 4;
}
```

Run the calculation on all measures and store the result in <code>sleep_1_p_numeric</code>.
```
Promise.all(promises).then( function() {
  var data = new DataFrame(allMeasures);
  data = data.map(row => row.set('sleep_1_p_numeric', mapNumeric(row.get('sleep_1_p'))));
  update(data, 'sleep_1_p_numeric');
});
```


<img width="1205" alt="image" src="https://user-images.githubusercontent.com/603956/47190011-32be8500-d2f4-11e8-95a0-a37e17d13e07.png">

**Comment by HaukeBartsch** [comment]
I have created bug#29 as an enhancement to improve on the non-sensical error message.
