### ISSUE TITLE
Ontology bug?

### ISSUE THREAD

**Issue by wkthompson123** [ABCD-STUDY/DEAP#62]
On the “Ontology” window, the two examples for searching include “intelligence”, but this term did not pull up any matches when I tried first. But I tried again later, and got 29 hits. Not sure what happened there, but reporting it just in case there’s a glitch.

**Comment by HaukeBartsch** [comment]
Let us know if that happens again. It might happen during a restart of the system - takes a while to have all the histogram files created which slows down processing. Maybe its caused by too many users using the search functionality at the same time. Hopefully NDA will be able to scale the system to all users to get the same speed.

**Comment by wkthompson123** [comment]
I think that may have caused it, it works for me now.
