### ISSUE TITLE
Race_Ethnicity 

### ISSUE THREAD

**Issue by Alejandrainfante** [ABCD-STUDY/DEAP#75]
is there a way to get the race breakdown for Hispanics only?

**Comment by HaukeBartsch** [comment]
Have a look how Hispanic is coded on https://github.com/ABCD-STUDY/analysis-nda17/blob/release-1.1/notebooks/derived/core_demographic.md#a-simplified-raceethnicity-value. It is using demo_ethn_p to calculate hispanic but it does encode for all the different races into demo_race_*. 

You could therefore create a new race variable merging the existing race variables (Extend) and Limit the analysis to the Hispanic population.

**Comment by Alejandrainfante** [comment]
Thank you! I will go ahead and try this.

**Comment by tashawade** [comment]
Hi Hauke,

I'm trying to help Alejandra calculate this. We created a summed race variables in extend and limited to Hispanic participants using race.eth="Hispanic". While both these steps worked, the data won't be analyzed using the new data no matter how I try it (with or without extend, with or without race/eth covariates automatically included, etc.). The error is always the same.

Thank you!

<img width="1907" alt="deapextendrace" src="https://user-images.githubusercontent.com/44237822/47673729-b5f09e00-db72-11e8-887d-31742b092b51.PNG">
<img width="962" alt="deaprace" src="https://user-images.githubusercontent.com/44237822/47673738-ba1cbb80-db72-11e8-8932-c7b8c7da2c6c.PNG">

**Comment by HaukeBartsch** [comment]
Your calculation should work. I don't understand the error message either. We will try to re-create this and try it on our end.

Summing them up would give you a value that is higher for participants that have endorsed more than one race checkbox. Just as another option you could also create a categorical variable instead of the sum by returning a string instead of a number. Here an example:
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/603956/47675812-2c43cf00-db78-11e8-9d03-7ddd9a643226.png">

The problem you can see there is that every Hispanic is white and perhaps something else.

**Comment by Mosqidiot** [comment]
I duplicated the same summed race variables in extend with exactly the same calculation. I successfully used this extended variable in the analysis application. Could you test it again by saving (click the save blue button) "summed race variable" and then try to access it through analysis?

**Comment by tashawade** [comment]
It worked this time without switching anything. Thanks!

**Comment by Mosqidiot** [comment]
Thanks for the confirmation.
